name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'

categories:
  - title: "🚀 Features"
    pull_request_title:
      - '^feat(?:\\([^)]*\\))?:'
  - title: "🐛 Fixes"
    pull_request_title:
      - '^fix(?:\\([^)]*\\))?:'
  - title: "🧹 Chores"
    pull_request_title:
      - '^chore(?:\\([^)]*\\))?:'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
