name: Commit Lint

on: [push, pull_request]

jobs:
  commitlint:
    runs-on: self-hosted  # or 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Commitlint
        run: npm install --global @commitlint/{cli,config-conventional}

      - name: Lint PR commits
        if: github.event_name == 'pull_request'
        run: |
          BASE_SHA="${{ github.event.pull_request.base.sha }}"
          HEAD_SHA="${{ github.event.pull_request.head.sha }}"
          if [ "$BASE_SHA" = "0000000000000000000000000000000000000000" ]; then
            npx commitlint --from "$HEAD_SHA" --config commitlint.config.js
          else
            npx commitlint --from "$BASE_SHA" --to "$HEAD_SHA" --config commitlint.config.js
          fi
        working-directory: ${{ github.workspace }}

      - name: Lint pushed commits
        if: github.event_name == 'push'
        run: |
          BEFORE_SHA="${{ github.event.before }}"
          SHA="${{ github.sha }}"
          if [ "$BEFORE_SHA" = "0000000000000000000000000000000000000000" ]; then
            npx commitlint --from "$SHA" --config commitlint.config.js
          else
            npx commitlint --from "$BEFORE_SHA" --to "$SHA" --config commitlint.config.js
          fi
        working-directory: ${{ github.workspace }}
