name: Commit Lint

on: [push, pull_request]

jobs:
  commitlint:
    runs-on: self-hosted  # Change to 'ubuntu-latest' if not using a self-hosted runner
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history for accurate commit range

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Commitlint
        run: npm install --global @commitlint/{cli,config-conventional}

      - name: Print working directory
        run: pwd

      - name: List files recursively
        run: ls -lR

      - name: Lint PR commits
        if: github.event_name == 'pull_request'
        run: |
          cd $GITHUB_WORKSPACE
          echo "Base SHA: ${{ github.event.pull_request.base.sha }}"
          echo "Head SHA: ${{ github.event.pull_request.head.sha }}"
          commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --config .commitlint.config.js

      - name: Lint pushed commits
        if: github.event_name == 'push'
        run: |
          cd $GITHUB_WORKSPACE
          echo "From: ${{ github.event.before }}"
          echo "To:   ${{ github.sha }}"
          commitlint --from ${{ github.event.before }} --to ${{ github.sha }} --config .commitlint.config.js
