name: Commit Lint

on: [pull_request]

jobs:
  commitlint:
    runs-on: self-hosted
    steps:
      - name: Commit lint
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: .commitlint.config.js
          platform: linux/arm64
